version: '3'
services:
  spark-master:
    image: polydeuce-sys/docker-spark
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
      - "6066:6066"
  spark-worker:
    image: polydeuce-sys/docker-spark
    depends_on: 
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER: spark://spark-master:7077
    ports:
      - "8081:8081"
